// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvYgZvsZX-DU-djFmxp0yXE_9_yuA6GPY',
    appId: '1:981420750189:web:bf4aeefb9bab70ba031664',
    messagingSenderId: '981420750189',
    projectId: 'bookmark-manager-24e55',
    authDomain: 'bookmark-manager-24e55.firebaseapp.com',
    storageBucket: 'bookmark-manager-24e55.firebasestorage.app',
    measurementId: 'G-LYLC3KJ4XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgUk6jxKKXA2yMh5NKxkXLLFmBt6l6bGo',
    appId: '1:981420750189:android:3e6a3c6c20ffaa50031664',
    messagingSenderId: '981420750189',
    projectId: 'bookmark-manager-24e55',
    storageBucket: 'bookmark-manager-24e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbrJGAIp7lrFQt4lV0qZ-zmDqZ0nZ8Zk4',
    appId: '1:981420750189:ios:908732b42b0ba76b031664',
    messagingSenderId: '981420750189',
    projectId: 'bookmark-manager-24e55',
    storageBucket: 'bookmark-manager-24e55.firebasestorage.app',
    iosBundleId: 'com.example.bookmarkManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbrJGAIp7lrFQt4lV0qZ-zmDqZ0nZ8Zk4',
    appId: '1:981420750189:ios:908732b42b0ba76b031664',
    messagingSenderId: '981420750189',
    projectId: 'bookmark-manager-24e55',
    storageBucket: 'bookmark-manager-24e55.firebasestorage.app',
    iosBundleId: 'com.example.bookmarkManager',
  );
}
